nifty = ['SBIN', 'TATASTEEL', 'DIVISLAB', 'KOTAKBANK', 'DRREDDY', 'ULTRACEMCO',
         'ITC', 'CIPLA', 'HDFCBANK', 'HINDUNILVR', 'SUNPHARMA', 'JSWSTEEL', 'NTPC',
         'HDFC', 'POWERGRID', 'BAJFINANCE', 'HINDALCO', 'NESTLEIND', 'ONGC', 'HDFCLIFE',
         'SBILIFE', 'BAJAJFINSV', 'RELIANCE', 'TITAN', 'BAJAJ-AUTO', 'ADANIPORTS',
         'GRASIM', 'INDUSINDBK', 'M&M', 'HEROMOTOCO', 'INFY', 'BPCL', 'WIPRO',
         'ASIANPAINT', 'TCS', 'LT', 'TECHM', 'HCLTECH', 'BRITANNIA', 'IOC', 'EICHERMOT',
         'SHREECEM', 'GAIL', 'ICICIBANK', 'MARUTI', 'UPL', 'COALINDIA', 'TATAMOTORS',
         'BHARTIARTL', 'AXISBANK']

nifty_below2000 = ['IOC', 'NTPC', 'ONGC', 'COALINDIA', 'GAIL', 'ITC', 'POWERGRID',
                   'HINDALCO', 'TATAMOTORS', 'JSWSTEEL', 'BPCL', 'SBIN', 'WIPRO',
                   'UPL', 'BHARTIARTL', 'SUNPHARMA', 'ICICIBANK', 'ADANIPORTS',
                   'TATASTEEL', 'HDFCLIFE', 'AXISBANK', 'CIPLA', 'SBILIFE', 'M&M',
                   'HCLTECH', 'TECHM', 'INDUSINDBK', 'GRASIM', 'INFY', 'TITAN',
                   'LT', 'HDFCBANK', 'KOTAKBANK', 'RELIANCE', 'HINDUNILVR']

nifty_below1000 = ['IOC', 'NTPC', 'ONGC', 'COALINDIA', 'GAIL', 'ITC', 'POWERGRID',
                   'HINDALCO', 'TATAMOTORS', 'JSWSTEEL', 'BPCL', 'SBIN', 'WIPRO',
                   'UPL', 'BHARTIARTL', 'SUNPHARMA', 'ICICIBANK', 'ADANIPORTS',
                   'TATASTEEL', 'HDFCLIFE', 'AXISBANK', 'CIPLA', 'SBILIFE', 'M&M',
                   'HCLTECH', 'TECHM', 'INDUSINDBK', 'GRASIM']

test_stocks = ['SBIN', 'TATASTEEL', 'DIVISLAB', 'KOTAKBANK', 'DRREDDY', 'ULTRACEMCO',
               'ITC', 'CIPLA', 'HDFCBANK', 'HINDUNILVR', 'SUNPHARMA', 'JSWSTEEL', 'NTPC']

mystocks = ['HDFCBANK', 'SBIN']

buzzing_stocks = ['WIPRO', 'KOTAKBANK', 'BIOCON', 'VIPCLOTHNG', 'GABRIEL', 'ELGIEQUIP', 'FLUOROCHEM', 'LT']

holdings = ['IRFC', 'ONGC']

recent_signals = ['IOC', 'ONGC', 'HINDALCO', 'SUNPHARMA', 'CIPLA', 'M&M', 'GAIL', 'UPL']

suggested = ['ASTRAZEN', 'HEROMOTOCO', 'INFY', 'INDIGO', 'CADILAHC', 'APOLLOHOSP', 'TATAELXSI']

todayq4 = ['ABB', 'AXISBANK', 'BAJAJFINSV', 'BRITANNIA', 'HDFCAMC', 'HINDZINC', 'MARUTI', 'TVSMOTOR', 'UBL']
